NAME_SELECTORS = ['//meta[@property="og:site_name"]/@content']
PUB_DATE_SELECTORS = ['//meta[contains(@name, "pub")]/@content', '//meta[contains(@property, "pub")]/@content', '//meta[@property="og:pubdate"]/@content', '//meta[@name="pubdate"]/@content']
DATE_FORMATS = ['%Y-%m-%dT%H:%M:%S.%fZ', '%Y-%m-%dT%H:%M:%SZ']
TITLE_SELECTORS = ['//h1/text()']
TITLE_DETAIL_SELECTORS = ['//meta[@property="og:description"]/@content']
IMAGE_SELECTORS = ['//meta[@property="og:image"]/@content']
AUTHOR_SELECTORS = ['//meta[@name="author"]/@content']